sets.exported={
    main="Naegling",
    sub="Ark Shield",
    ammo="Aurgelmir Orb",
    head="Meghanada Visor +1",
    body="Meg. Cuirie +1",
    hands="Meg. Gloves +1",
    legs="Meg. Chausses +2",
    feet="Meg. Jam. +1",
    neck="Sanctity Necklace",
    waist="Windbuffet Belt +1",
    left_ear="Cessance Earring",
    right_ear="Mache Earring",
    left_ring="Petrov Ring",
    right_ring="Tali'ah Ring",
    back="Buquwik Cape",
}