sets.exported={
    main="Naegling",
    sub="Blurred Shield",
    ammo="Staunch Tathlum",
    head="Sulevia's Mask +1",
    body="Sulevia's Plate. +1",
    hands="Sulev. Gauntlets +2",
    legs="Sulev. Cuisses +2",
    feet="Sulev. Leggings +1",
    neck={ name="War. Beads +1", augments={'Path: A',}},
    waist="Ioskeha Belt",
    left_ear="Cessance Earring",
    right_ear={ name="Boii Earring", augments={'System: 1 ID: 1676 Val: 0','Accuracy+9','Mag. Acc.+9',}},
    left_ring="Sulevia's Ring",
    right_ring="Warden's Ring",
    back={ name="Cichol's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}